version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: fusionauth
      POSTGRES_PASSWORD: fusionauth
      POSTGRES_DB: fusionauth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - db
    ports:
      - "9011:9011"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_USERNAME: fusionauth
      DATABASE_PASSWORD: fusionauth
      FUSIONAUTH_APP_MEMORY: 512M

volumes:
  pgdata:
